version: '3'
services:
  extension-1:
    image: <your-extension-image>
    ports:
      - 50055:50051
    restart: on-failure

  kwil:
    image: kwildb/kwil:v0.6.1
    ports:
      - 8080:8080
    depends_on:
      - extension-1
    restart: on-failure
    command: |
      --autogen
      --app.extension-endpoints=extension-1:50051
      --app.http-listen-addr=0.0.0.0:8080
